### ISSUE TITLE
overflow when reading sensors 

### ISSUE THREAD

**Issue by geofrancis** [RobTillaart/INA228#10]
I get inconsistent readings with my 2 sensors, 

![image](https://github.com/user-attachments/assets/538890f1-e496-442e-84ae-7242cb90874d)

**Comment by RobTillaart** [comment]
Thanks for reporting the issue,

What is your question?

As I have no information but this screenshot it is impossible to determine a cause.

Which version of the library?
There are several fixes in the latest version 0.1.2.

Which board do you use?
Which sketch running?
What constructor do you use? 
Does that match the shunt near the INA228?

**Comment by geofrancis** [comment]
I am using a pair of these sensors to measure a 13s(48v) battery https://www.mateksys.com/?portfolio=i2c-ina-bm

when testing with a modified version of the demo program.


`#include "INA228.h"

INA228 INA1(0x45);
INA228 INA2(0x44);

void setup() {
  Serial.begin(115200);
  Serial.println(__FILE__);
  Serial.println();
  Serial.print("INA228_LIB_VERSION: ");
  Serial.println(INA228_LIB_VERSION);
  Serial.println();

  Wire.begin();
  if (!INA1.begin()) {
    Serial.println("Could not connect. Fix and Reboot");
    while (1)
      ;
  }
}


void loop() {
  Serial.println("\nBUS\tSHUNT\tCURRENT\tPOWER\tTEMP");

  Serial.print(INA1.getBusVoltage(), 3);
  Serial.print("\t");
  Serial.print(INA1.getShuntVoltage_mV(), 3);
  Serial.print("\t");
  Serial.print(INA1.getCurrent_mA(), 3);
  Serial.print("\t");
  Serial.print(INA1.getPower_mW(), 3);
  Serial.print("\t");
  Serial.print(INA1.getTemperature(), 3);
  Serial.println();

  delay(1000);

  Serial.println("\nBUS\tSHUNT\tCURRENT\tPOWER\tTEMP");

  Serial.print(INA2.getBusVoltage(), 3);
  Serial.print("\t");
  Serial.print(INA2.getShuntVoltage_mV(), 3);
  Serial.print("\t");
  Serial.print(INA2.getCurrent_mA(), 3);
  Serial.print("\t");
  Serial.print(INA2.getPower_mW(), 3);
  Serial.print("\t");
  Serial.print(INA2.getTemperature(), 3);
  Serial.println();
  Serial.println();
  Serial.println();
  Serial.println();

  delay(1000);
}
`

this is the output

20:12:55.594 -> BUS	SHUNT	CURRENT	POWER	TEMP
20:12:55.594 -> 50.296	327.648	ovf	103.577	0.023
20:12:56.584 -> 
20:12:56.584 -> BUS	SHUNT	CURRENT	POWER	TEMP
20:12:56.675 -> 52428.801	20971.520	ovf	262144000.000	33554.434

**Comment by geofrancis** [comment]
updated it, its not overflowing now but the decimal is not where it should be

![image](https://github.com/user-attachments/assets/9e5fb22e-79d5-46b2-ba18-523ca7139c2f)

**Comment by RobTillaart** [comment]
You need to call **setMaxCurrentShunt(float maxCurrent, float shunt)** for both of the sensors in **setup()**

```cpp
INA1.setMaxCurrentShunt(20, 0.02);  //  adjust to your specs
INA2.setMaxCurrentShunt(20, 0.02);  //  adjust to your specs
```

**Comment by geofrancis** [comment]
I have that in the latest version 

````
//
//    FILE: INA228_demo.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: demo core functions
//     URL: https://github.com/RobTillaart/INA228


#include "INA228.h"


INA228 INA1(0x45);
INA228 INA2(0x44);


void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);
  Serial.println();
  Serial.print("INA228_LIB_VERSION: ");
  Serial.println(INA228_LIB_VERSION);
  Serial.println();

  Wire.begin();
  if (!INA1.begin() )
  {
    Serial.println("Could not connect. Fix and Reboot");
    while(1);
  }

  INA1.setMaxCurrentShunt(10, 0.015);
  INA2.setMaxCurrentShunt(10, 0.015);
}


void loop()
{
  Serial.println("\nBUS\tSHUNT\tCURRENT\tPOWER\tTEMP");

    Serial.print(INA1.getBusVoltage(), 3);
    Serial.print("\t");
    Serial.print(INA1.getShuntVoltage_mV(), 3);
    Serial.print("\t");
    Serial.print(INA1.getCurrent_mA(), 3);
    Serial.print("\t");
    Serial.print(INA1.getPower_mW(), 3);
    Serial.print("\t");
    Serial.print(INA1.getTemperature(), 3);
    Serial.println();
    delay(1000);
 Serial.println("\nBUS\tSHUNT\tCURRENT\tPOWER\tTEMP");
    Serial.print(INA2.getBusVoltage(), 3);
    Serial.print("\t");
    Serial.print(INA2.getShuntVoltage_mV(), 3);
    Serial.print("\t");
    Serial.print(INA2.getCurrent_mA(), 3);
    Serial.print("\t");
    Serial.print(INA2.getPower_mW(), 3);
    Serial.print("\t");
    Serial.print(INA2.getTemperature(), 3);
    Serial.println();
    delay(1000);


  
}


//  -- END OF FILE --
````

**Comment by geofrancis** [comment]
i updated the shunt to the correct 0.002 value, its not really changed anything.
![image](https://github.com/user-attachments/assets/7de84c59-5a5c-4f9d-8fb5-29323a4e8266)

**Comment by RobTillaart** [comment]
You can change these two lines to have a more readable sensor 1

```cpp
    Serial.print(INA1.getCurrent(), 3);
    Serial.print("\t");
    Serial.print(INA1.getPower(), 3);
```

**Comment by RobTillaart** [comment]
> I have that in the latest version, that shouldnt effect the voltage. why is sensor 1 50.29 and the sensor 2 is 52428.428 ?

Add to **setup()** a test to see if you can see INA2 on the I2C bus. My guess is it is not.

```cpp
  if (!INA2.begin() )
  {
    Serial.println("Could not connect INA2. Fix and Reboot");
    while(1);
  }
```

**Comment by RobTillaart** [comment]
I noted that the current is **19806.252 mA** so you have to set this correctly in **setup()**

```cpp
 INA1.setMaxCurrentShunt(30, 0.015);
```

**Comment by geofrancis** [comment]
I just tested each one individually and one had the wrong address, changing that has improved things, so you're correct that the second sensor wasn't detected. I just would have expected it to return 0 instead of numbers like that 

![image](https://github.com/user-attachments/assets/e60ff11a-23e1-4582-8af8-b1ea9ea99a19)


````
void loop() {
  Serial.println("\nBUS\tSHUNT\tCURRENT\tPOWER\tTEMP");

  Serial.print(INA1.getBusVoltage());
  Serial.print("\t");
  Serial.print(INA1.getShuntVoltage_mV());
  Serial.print("\t");
  Serial.print(INA1.getCurrent_mA());
  Serial.print("\t");
  Serial.print(INA1.getPower_mW());
  Serial.print("\t");
  Serial.print(INA1.getTemperature());
  Serial.println();
  delay(1000);
  Serial.println("\nBUS\tSHUNT\tCURRENT\tPOWER\tTEMP");
  Serial.print(INA2.getBusVoltage());
  Serial.print("\t");
  Serial.print(INA2.getShuntVoltage_mV());
  Serial.print("\t");
  Serial.print(INA2.getCurrent_mA());
  Serial.print("\t");
  Serial.print(INA2.getPower_mW());
  Serial.print("\t");
  Serial.print(INA2.getTemperature());
  Serial.println();
  Serial.println();
  Serial.println();
  Serial.println();
  delay(1000);
}
````

**Comment by RobTillaart** [comment]
Except for the layout (Amps vs milliAmps etc) the values look reasonable.

> ... correct that the second sensor wasn't detected. I just would have expected it to return 0 instead of numbers like that

returning zero would be equally incorrect, and yes it would look nicer.
However the chance of an erroneous  value slipping through unnoticed would be great(er).

I would need to add a call to isConnected() in every call to check if the sensor is still visible. That would reduce throughput / performance quite a bit.

**Comment by RobTillaart** [comment]
> INA1.setMaxCurrentShunt(204.8, 0.0002);
> INA2.setMaxCurrentShunt(204.8, 0.0002);

My mistake,  the max current of the INA228 is 10A, 
I messed up with another sensor, my mistake sorry.

In fact you can test the return value to see it went OK.
See readme.md file

- **int setMaxCurrentShunt(float maxCurrent, float shunt)** 
maxCurrent = 0..10A, shunt = 0.0001 .. ?? 
  - returns 0 if OK.
  - returns -1 if maxCurrent > 10 Ampere
  - returns -2 if shunt < 0.0001 Ohm.

in code
```cpp
if (INA1.setMaxCurrentShunt(10, 0.0002) != 0) Serial.println("error");
if (INA2.setMaxCurrentShunt(10, 0.0002) != 0) Serial.println("error");
```

**Comment by geofrancis** [comment]
so i rescaled everything to amps  and its almost all looking perfect apart from sensor 1 current reading, the watts looks reasonable but current is showing 20A

![image](https://github.com/user-attachments/assets/c2809f6a-bfa2-4fe5-974d-4f1312e4c95f)

**Comment by geofrancis** [comment]
I swapped adresses around in software and the strange current reading is only on that sensor 

![image](https://github.com/user-attachments/assets/f7e24625-1052-47f8-b0f8-33b6671538f0)

**Comment by RobTillaart** [comment]
Sensor (shunt?) might be broken as the voltage over the shunt is too high

![image](https://github.com/user-attachments/assets/35f85368-2d6c-4cd2-b84d-cb81c7410392)

**Comment by geofrancis** [comment]
it does look strange with the high shunt voltage, il order another one its just strange that the miliwatts reading looks reasonable 

![image](https://github.com/user-attachments/assets/1968628d-6f43-44f9-830c-a06341086370)

**Comment by geofrancis** [comment]
I left it running for a while and goes between zero and 19.99A
![image](https://github.com/user-attachments/assets/86a59e63-dc42-4b57-a613-9b96265cba3a)

**Comment by geofrancis** [comment]
some more information, from testing it seems that the large error in the current reading only happens when the current is going the other way, like when im charging the battery it will show that large error current value but the power is accurate .

**Comment by RobTillaart** [comment]
>  does the sensor support negative values?

From my head, no
The sensor has a + and - input..
What does the datasheet say?

Note: 327.66 is numerically very close to an 16 bit int max value of 32767 (scaled).

**Comment by RobTillaart** [comment]
Power comes from another register of the chip, it is not calculated by the library code.

**Comment by geofrancis** [comment]
ok thank you.

**Comment by RobTillaart** [comment]
> Note: 327.66 is numerically very close to an 16 bit int max value of 32767 (scaled).

Need to investigate this, library may detect this or at least it deserves a few lines in the readme.md

**Comment by RobTillaart** [comment]
datasheet P.13

**7.3.4 High-Precision Delta-Sigma ADC**
_The integrated ADC is a high-performance, low-offset, low-drift, delta-sigma ADC designed to support
bidirectional current flow at the shunt voltage measurement channel._

So it should be possible to measure negative current flows

**Comment by geofrancis** [comment]
`My mistake, the max current of the INA228 is 10A,`


the current limit of the sensor is not 10A, that was just example values from the datasheet for a theoretical 10A sensor.

**Comment by RobTillaart** [comment]
> my sensor is rated to 204A.

Where in the datasheet can I find this?

The datasheet only has references to 10A and therefor the **setMaxCurrentShunt()** is limited to 10A in the INA228.cpp file.

You can comment line 338 in INA228.cpp 
```cpp
  if (maxCurrent > 10) return -1;  //  TODO error code
```

I am happy to change the limit if I got a good reference that explains the maximum current value.

**Comment by geofrancis** [comment]
its in the link i posted 
https://www.mateksys.com/?portfolio=i2c-ina-bm

**Comment by RobTillaart** [comment]
This is a completely different board as I have (Adafruit), and given the connectors and the width of the traces.... Yes that can handle 200 Amps.

So I have to update the code and the readme.md, add some links etc. will create a develop branch asap.

Thanks for this information,

**Comment by RobTillaart** [comment]
@geofrancis 
Created a develop branch + PR which removes the 10 A limit for the maxCurrent. 
Added the 2 device code above as additional example and updated the readme.md.

**Comment by RobTillaart** [comment]
For completeness, 
the Adafruit INA228 I used for testing is limited to 10 A, see - https://www.adafruit.com/product/5832

**Comment by RobTillaart** [comment]
@geofrancis 

Did some tests this morning and fixed the negative values for **getCurrent()** and **getShuntVoltage()** in the develop branch.
Please verify.

If it is OK, you should remove your hack
```
I have just added a hack for if (ma>19000) {ma= -1;} 
```

**Comment by geofrancis** [comment]
that all looks good now.

**Comment by RobTillaart** [comment]
> that all looks good now.

Then I will start merge and release 0.1.3 
If other problems occur please open a new issue!

**Comment by RobTillaart** [comment]
@geofrancis 
Again thanks for your testing and feedback, appreciated!
