### ISSUE TITLE
INA228

### ISSUE THREAD

**Issue by caoxuan19961206** [RobTillaart/INA228#2]
Hello,

I was curious if there is a INA228 of this driver being developed (or in the pipeline) for this chip?

Respectfully,
RobTillaart

**Comment by RobTillaart** [comment]
@caoxuan19961206 

Moved the issue to the new INA228 repository so it has the right context.

**Comment by RobTillaart** [comment]
@caoxuan19961206 

Added quite some functionality to the library.
If you have time, please verify if it works.

**Comment by RobTillaart** [comment]
@caoxuan19961206 

Develop branch is now functionally complete.
If you have time, please verify if it works.

**Comment by caoxuan19961206** [comment]
Thank you very much for helping me. I have tested INA228_demo and INA228_dump_config, and they can work normally

**Comment by RobTillaart** [comment]
@caoxuan19961206 

Thanks for testing!
I hope that the values you got make sense and are accurate.

One more question, which board do you use?

**Comment by RobTillaart** [comment]
@caoxuan19961206 

A new 0.1.3 version released today, fixes a few bugs so have a look.
